language: ruby

rvm:
- 2.2.1

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id: AKIAJ5QHVYAIUFE23NKQ
  secret_access_key:
    secure: QwtneLAK4q3Ah0ughVuQA+y9/GHNsMau79X+9yLW2kH4UH2Ov+4UzgjYr1b+hov+LgqUAvOT0b3b1FPNb0T6qCRO/Xtjp48SCC7d3Hbyl1Bc4Wb1afIdxF5SAKkQ9cTl/CYWIKf5XTFq3FVKLto/QVSbB6ik5MJvWVuakHnAQSiaimrFex21mLjfj5FyK1QB/8jfezJxcmNauTZEvVuHylQOUL/ZXcc02yjV/tellv0QzTpqjhwP8rxqKI48YbEwAZkBYEfsSWL7WKr0MxP5fF7XCu2mUZTq+XPiiAoGRdE9JzMpGFuodAX6akeDt33E2h98cVabiu2Q10khYDNy/vYEFDDhC1GQ3WHiYRiDWfqNvbs5/BvWntVDVYnO6dEZaxNi5q76SHJgeeoWrhRMGzJz+Vog65FQwDKiUnsAX57ea5Jsrm4o9Ld8bD/hX/vJEllOHwOVof/nn60fdrDvF8vQzYy6S+iJmRaeRE/dZMOWh7ih0kutCQj9/EwM13VJkwhXMipaVD+yCOarrsCsl4ZdnD/D56p758ju0m/yQQSk/x4QdOEvMWj5DtVz3t7/wtsNyHsXI7gfn9lr03pC9gOb7YGs8OgKs2qEehClHtF6nWqLoCfQu8Nbm9DyOYuVmriRDBw1woRJmSkjiozVlT39SnuJfTqjyM8BwGZbqWc=
  bucket: www.knittedbysteph.com
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
